### ISSUE TITLE
Transfer to theleagueof GitHub org

### ISSUE THREAD

**Issue by davelab6** [theleagueof/leaguemono#5]
I think this will help users find this repo

**Comment by sursly** [comment]
Pretty sure The League is just pulling in my master, so I think that one is up to Micah

**Comment by sursly** [comment]
@micahbrich - checking in here. I think the League repo is WAY different than what I have going here.

**Comment by alerque** [comment]
The League's repo is very out of date. I think we should do a swap and make this canonical for all further development.

1. Move the current League repo out of the way.
2. Do a namespace transfer to move this repo (since it is what Github knows as the project root, has issues, more stars, etc.) into the League namespace.
3. See if anything got missed in the League's fork that could be copied back here.
4. Two options here: ⋮ⓐ My suggestion would be to do nothing, Github will automatically forward all incoming links (including git access) to your repo to the new location. Or ⓑ you could clone it back yourself (people would then possible be ending up on a clone rather than the canonical one).

**Comment by afcowie** [comment]
@alerque 's suggestion 1+2 is the way to do this (I move repos between organizations quite frequently, usually to promote them from my own namespace to a shared one). No need for 4 because of the redirects they put in place.

**Comment by sursly** [comment]
I've made several updates to this project lately, and have a few more I'm looking to push out. It might make sense to wait a little bit longer if you can.

**Comment by micahbrich** [comment]
@sursly I'm definitely on board with this — I've been regretting how much of a roadblock I've been in updating in the name of promoting stuff; if you're down with it, I'd rather have it in the team repo but give you complete access so you can update whenever you want, which would mean you could push those updates even after moving the repo. That would go for all of them, I'll make sure you have total access, this just happens to be the only repo that's not attached to the League team.

What chu think? You down?

**Comment by sursly** [comment]
🤷‍♂️
I'm not sure! Not sure I feel like doing anything just yet. Got more changes to make.

**Comment by alerque** [comment]
So maybe it's not time to tag and publicize a new release, but the repository shuffling could still happen so that the league repo is canonical and shows the current development status. The sooner this shuffling is done the better I think, and work on the actual font can continue and a release can be tagged when you feel it's an a point in development that people should start using it.

**Comment by afcowie** [comment]
@sursly (if the repo moves to another Org you can continue to contribute to it the same as before [provided the owner of that Org sets up a "team" such that you have `Write` access to that repo])

**Comment by sursly** [comment]
OK, so what now then? Does this repo go away (not ideal)?

**Comment by alerque** [comment]
Not exactly. You use Github's transfer feature to change the namespace. Github will handle redirects for everybody linking old URL's transparently (this includes `git` operations, issues, everything).

First @micahbrich needs to rename the current `theleagueof/leaguemono` repository out of the way somewhere, then give you (if you don't already have it) write access to the `theleagueof` namespace, then you can go into settings for this repository and use the "Transfer Ownership* feature to move it to the org.

**Comment by sursly** [comment]
OK so once Micah gets things rolling I'll do my thing. 
Question: I put a sponsorship.yml file in this repo, but it probably shouldn't be in the league repo (or if it is, it should be changed to fund the league maybe?). That raises another question about funding/support which makes me think the main project should stay with the font authors and the league forks its own version.
But who knows.

**Comment by alerque** [comment]
I guess we'll have to take that up with @micahbrich, but personally I'd be all for you keeping the sponsor link active pointing at your personal info even from inside the repo in the league namespace. I don't see any other way that's fair to font creators. *Possibly* an additional link for the league itself could be added, but at least the primary designer and in some cases others who make significant contributions to a font should be able to list their sponsor links — at least by my way of thinking.

**Comment by alerque** [comment]
@micahbrich From experience on another project, just renaming this inside the org won't help, I think it needs to be moved out of the league namespace before Tyler can transfer his repo here. Maybe transfer this fork to your personal Github namespace. Then make sure Tyler has the ability to start new / transfer repos to this org.

**Comment by micahbrich** [comment]
Okay @sursly I thinkkkkkk you should have permission to make new repos and read/write to any league repo. 

<img width="774" alt="Screen Shot 2020-08-28 at 2 52 12 PM" src="https://user-images.githubusercontent.com/25366/91605242-236fe000-e93e-11ea-81c7-9f6fe471eb3c.png">

Since the existing site links to the existing repo, rather than renaming the old repo, updating the code for the old site, moving the new repo in, updating the code again — maybe a more efficient way is to keep the old repo named `theleagueof/leaguemono`, and just make the _new_ one `theleagueof/league-mono`. Once it's moved over, it's just one site update and I can archive/delete the old one without any downtime or extra website updates.

Does that sound okay @sursly @alerque?

**Comment by micahbrich** [comment]
Okay JK @alerque is saying we can't have two league monos in the github org. So I'm gonna have to have to move the current one to my personal account, update the site code, then wait for tyler to move it, then once he does, update the site again. so let me work on that later tonight.

**Comment by alerque** [comment]
Nope, can't have two copies of the same repository in the same namespace even if you give them different names. But no worries about the site code either. Automatic redirects will have you covered.

**Comment by micahbrich** [comment]
Oh my goodness, @alerque is a genius. Forget everything I said, I transferred the existing one to [micahbrich/league-mono](https://github.com/micahbrich/league-mono) and downloads/the site are still working cuz it redirects, so we are GOOD. 🙏 I appreciate you.

**Comment by alerque** [comment]
Paging @sursly — namespace clear, ready for incomming transfer! When you transfer this repo into @theleagueof namespace if you can also rename it `league-mono` (with the dash) at the same time that would be great. If it doesn't let you do two actions at once that's okay, we can fix the naming first thing when it comes across.

**Comment by micahbrich** [comment]
@sursly is there anything you need from me to help make this happen?

**Comment by sursly** [comment]
hold on to ur butts
<img width="543" alt="Screen Shot 2020-09-02 at 11 59 46 AM" src="https://user-images.githubusercontent.com/710829/92007474-03606800-ed14-11ea-9bec-e20f12b0b95e.png">

**Comment by sursly** [comment]
Note: in transferring ownership I wasn't prompted with the option of renaming it. You might as well just rename the repo since we've already been mucking around in the Github **_danger zone_**.

**Comment by alerque** [comment]
Hurray! Sorry I've been on vacation and am just seeing this. @micahbrich I don't have permissions on this repo yet like I do on the other League repos, I'm guessing you checked them off as part of a team or something. If you saddle me up I'll get to work on bringing this up to speed. You can either take care of the repo rename yourself or I'll do it when I get permissions.

**Comment by micahbrich** [comment]
> Hurray! Sorry I've been on vacation and am just seeing this. @micahbrich I don't have permissions on this repo yet like I do on the other League repos, I'm guessing you checked them off as part of a team or something. If you saddle me up I'll get to work on bringing this up to speed. You can either take care of the repo rename yourself or I'll do it when I get permissions.

Boom, @alerque did that work? Changed Core team from read to admin.

**Comment by alerque** [comment]
Yessums. (And this repo's name is now graced with a hyphen.)
